### ISSUE TITLE
Level Select Visual Bug

### ISSUE THREAD

**Issue by BlaznTheKid** [Carth501/team-ferret#113]
**Describe the bug**
When completing a level and brought to the menu select Rolodex, it looks like the checkmark symbol doesn't show up properly but as its unicode number. Also the manual appears on the level select (unless this was intended)

**To Reproduce**
1. Go to the web version of the game: https://fourgoblinsinatrenchcoat.itch.io/think-of-the-shareholders-web
2. Complete the tutorial level Orientation
3. See error on level select

**Screenshots**

![RoloDex Bug](https://github.com/Carth501/team-ferret/assets/161366272/9f07bb75-37cb-48fc-8997-54e305ac0e02)

**Environment**
 - Windows
 - Web

**Additional context**
Possible fix to use images to indicate completion as opposed to characters

**Comment by Carth501** [comment]
fixed in https://github.com/Carth501/team-ferret/pull/116
